
services:
  app.api:
    container_name: app.api
    ports:
      - "3000:3000"

  mongodb:
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      -  .env
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}"